table dim_sistema

	column sistema_id
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: sistema_id

	column codigo
		dataType: string
		summarizeBy: none
		sourceColumn: codigo

	column nombre
		dataType: string
		summarizeBy: none
		sourceColumn: nombre

	column es_peninsular
		dataType: boolean
		summarizeBy: none
		sourceColumn: es_peninsular

	partition dim_sistema = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaDatos & "dim_sistema.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    Columnas = Table.SelectColumns(Encabezados, {"sistema_id", "codigo", "nombre", "es_peninsular"}),
				    Booleanos = Table.TransformColumns(Columnas, {{"es_peninsular", each _ = "t", type logical}}),
				    Tipos = Table.TransformColumnTypes(Booleanos, {{"sistema_id", Int64.Type}, {"codigo", type text}, {"nombre", type text}}, "en-US")
				in
				    Tipos
