table fact_generacion_total

	column fecha_id
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: fecha_id

	column sistema_id
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: sistema_id

	column mwh_total
		dataType: double
		formatString: #,0.0
		summarizeBy: none
		sourceColumn: mwh_total

	partition fact_generacion_total = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaDatos & "fact_generacion_total.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    Columnas = Table.SelectColumns(Encabezados, {"fecha_id", "sistema_id", "mwh_total"}),
				    Tipos = Table.TransformColumnTypes(Columnas, {{"fecha_id", Int64.Type}, {"sistema_id", Int64.Type}, {"mwh_total", type number}}, "en-US")
				in
				    Tipos
